services:
  - type: web
    name: n8n-server
    env: docker
    plan: free
    repo: https://github.com/romaferro/n8n-docker2
    branch: main
    dockerfilePath: ./Dockerfile
    envVars:
      - key: N8N_BASIC_AUTH_ACTIVE
        value: true
      - key: N8N_BASIC_AUTH_USER
        value: admin
      - key: N8N_BASIC_AUTH_PASSWORD
        value: password

GitHub (https://github.com/romaferro/n8n-docker2)
GitHub - romaferro/n8n-docker2
Contribute to romaferro/n8n-docker2 development by creating an account on GitHub.
